### ISSUE TITLE
Basic Auth does not seem to work as in Swagger

### ISSUE THREAD

**Issue by iasisalomon** [Rhosys/openapi-explorer#10]
Trying out Basic auth, it does not seem to work at all. 
Does this functionality require additional setup?

**Comment by wparad** [comment]
Should work, we'll take a look and see if there is anything off about it. Just to make sure that we are validating it correctly do you have a sample spec which isn't working to share?

**Comment by iasisalomon** [comment]
Paste an image because I can't copy it all.
Sorry for the inconveniences.
[https://imgur.com/a/zp4PvOX](url)
[https://imgur.com/a/U7tckaH](url)

**Comment by wparad** [comment]
There was an issue, I've just pushed out a new version which will have this resolved.

=> `0.1.114`
