### ISSUE TITLE
Enable selecting the server for each operation request

### ISSUE THREAD

**Issue by nikitapatel029** [Rhosys/openapi-explorer#101]
I tried to put list of API server at operations(API) level, but still it is showing on top only, ideally it should give features to select under each and every api as it might be things we are having multiple server and for different APIS we might need to run on different server.

Thank you.

**Comment by wparad** [comment]
If I understand correctly you would want to the user to pick the server at the operation request for use with executing against that server. That isn't implemented as far as I know, but it would be possible for you to use a slot to configure a custom component and set the url accordingly.

Would that be feasible for your use case?

**Comment by nikitapatel029** [comment]
Does custom components work in middle of page? I wanted to keep server url selection before/after the request body so before executing request user can select particular server for that request.

**Comment by wparad** [comment]
Check out `<slot name="${pathElementId}"></slot>` where `pathElementId` you can grab from the website url when you navigate there. If you edit that you'll get a section that is right about in the middle of the page.
