### ISSUE TITLE
Feature request- should show response with examples under request 

### ISSUE THREAD

**Issue by nikitapatel029** [Rhosys/openapi-explorer#102]
It would be good if tool can provide features to show response with examples.

I tried to put some response example with code, description & value but it is not showing, it would be really awesome if tool can support this feature. 

Note- I've tried with yaml file

**Comment by wparad** [comment]
The responses do show the model and examples:

![image](https://user-images.githubusercontent.com/5056218/189874382-933e70ec-9c74-4567-9911-92ece515a531.png)

If something isn't working for you can you share a minimal reproduction so we can look into it?

**Comment by nikitapatel029** [comment]
I am not sure whether it is with yaml file or not, I just tried with "https://assets.zuora.com/zuora-documentation/swagger.yaml" and still didn't able too see response tab, can you please confirm from your side ?

**Comment by wparad** [comment]
Some of the responses didn't have a schema so this was throwing an error, I'm fixing that in a PR. However there's a problem with the `responses` object.

The library expects the responses object to be in the format:
```yaml
      responses:
        '200':
          content:
            "application/json":
              schema:
                $ref: '#/definitions/CommonResponseType'
```

For displaying the model, instead of:
```yaml
       responses:
         '200':
           schema:
            $ref: '#/definitions/CommonResponseType'
```

Which hopefully would be an easy change on your side.
