### ISSUE TITLE
Support for Next.js

### ISSUE THREAD

**Issue by cathoderay** [Rhosys/openapi-explorer#106]
I've tried to use the package in a `Next.js` project but, after installing and importing it in `pages/index.js` like:
```
import 'openapi-explorer';
```
I get the following error in the browser:
```
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'full-path-ommited/nextjs-test/node_modules/openapi-explorer/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

**Comment by wparad** [comment]
You can either switch to using nodejs modules, or you can pull in the already bundled version: `require('openapi-explorer/dist/browser/openapi-explorer.min.js')`. Let us know if either of those solutions aren't working.

**Comment by cathoderay** [comment]
Thank you very much @wparad! I'll try it and let you know.
