### ISSUE TITLE
Issue with `computedUrl` change in `0.10.428`

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#109]
Something that was implemented in `0.10.428` is breaking how the spec file is now being loaded.  When building against `0.10.426` it works fine, but any build after `0.10.426` results in the following error:

```
OpenAPI Explorer: Unable to resolve the API spec.. TypeError: Cannot read properties of undefined (reading 'computedUrl')
```

@wparad you can see the issue on the sandbox setup that I previously provided for the other issue with custom-nav.  I have updated the `package.json` file to use `0.10.432` but it's still failing.  If there is something I need to do on my end because of what was changed in `0.10.428` please let me know.

[sandbox URL](https://codesandbox.io/s/sad-shadow-ju9u07])

![image](https://user-images.githubusercontent.com/26559157/193823954-4dbeb06a-226e-4fe8-ba79-4febd706b45f.png)

**Comment by wparad** [comment]
No idea if something changed on your side or our side. We are just going to increase the defensive use of `computedUrl` so this should be a problem. If there is a still an issue, feel free to comment here after the update from 590c903.

**Comment by silverbullettruck2001** [comment]
@wparad That fixed it!  Thanks!
