### ISSUE TITLE
Multiple language support, server side rendering

### ISSUE THREAD

**Issue by iasisalomon** [Rhosys/openapi-explorer#11]
Does the package support server side rendering? (nuxt, next). We need this functionality for indexation purposes.

Does the package support automatic generation of multiple languages for api calls (beyond cURL)? If not, is there any way you recommend to implement this functionality?

**Comment by wparad** [comment]
> Does the package support server side rendering? (nuxt, next). We need this functionality for indexation purposes.
Yes, but if you run into something specific feel free to create a dedicated issue for that.

> Does the package support automatic generation of multiple languages for api calls (beyond cURL)? If not, is there any way you recommend to implement this functionality?

Do you mean programming languages for SDK examples or something else?

**Comment by iasisalomon** [comment]
Yes, support to generate automatically generate code for Axios, Fetch, PHP, etc.

**Comment by wparad** [comment]
> Yes, support to generate automatically generate code for Axios, Fetch, PHP, etc.

Right it supports it as an extension. For instance, you can specify the code sample in the document and that will get pulled in:
* [Server side code generation](https://github.com/ErikWittern/openapi-snippet)
* [Code sample display](https://github.com/Rhosys/openapi-explorer/blob/release/0.2/docs/documentation.md#sdk-code-samples)

So the server would generate the code sample blob (or statically include in your doc) and then it would get rendered in the explorer.

Does that work for you?

**Comment by iasisalomon** [comment]
I think it does. Will try to apply it to the documentation and close the issue when OK.

**Comment by iasisalomon** [comment]
Could this be a bug?
![Screenshot from 2021-04-19 13-59-46](https://user-images.githubusercontent.com/48367845/115274919-8f929480-a117-11eb-874c-bcbd40532d2f.png)
![Screenshot from 2021-04-19 13-59-30](https://user-images.githubusercontent.com/48367845/115274924-90c3c180-a117-11eb-809e-f1e380acc007.png)

**Comment by wparad** [comment]
> Could this be a bug?
> ![Screenshot from 2021-04-19 13-59-46](https://user-images.githubusercontent.com/48367845/115274919-8f929480-a117-11eb-874c-bcbd40532d2f.png)
> ![Screenshot from 2021-04-19 13-59-30](https://user-images.githubusercontent.com/48367845/115274924-90c3c180-a117-11eb-809e-f1e380acc007.png)

Could you explain a bit about what here is the bug, it isn't exactly obvious for me what you are showing.

**Comment by iasisalomon** [comment]
When I generate the x-code-sample attribute in openApi and copy the generated code in many languages, it only styles the first code described from the array

**Comment by wparad** [comment]
> When I generate the x-code-sample attribute in openApi and copy the generated code in many languages, it only styles the first code described from the array

Ah, it shouldn't be only the first one, but it should be "only the languages that are recognized". If you want to provide multiple samples for the same language, it should work to repeat like:
```json
"x-code-samples": [{
    "lang": "javascript",
    "label": "JS + Axios",
    "source": "console.log('This is a code sample')"
}, {
    "lang": "javascript",
    "label": "JS + Fetch",
    "source": "console.log('This is a code sample')"
}]
```

**Comment by iasisalomon** [comment]
Great! Thanks for so much help!
