### ISSUE TITLE
How to inject existing Auth Token to each request

### ISSUE THREAD

**Issue by satyam-bala** [Rhosys/openapi-explorer#110]
As per this doc page - https://github.com/Rhosys/openapi-explorer/blob/main/docs/documentation.md
it is mentioned to inject with @request. 

I have the below code snippet in my home.html
`<openapi-explorer spec-url="/v3/api-docs/users/" @request="requestInterceptor"></openapi-explorer>`
the question is where to write the `requestInterceptor(event)` function. 

```
requestInterceptor(event) {
  event.detail.request.headers.append('Authorization', 'Bearer ${userToken}');
}
```

Appreciate your help.

**Comment by wparad** [comment]
It would depend on your framework. Are you using Vue, React, vanilla js, or something?

**Comment by satyam-bala** [comment]
Iam using just venila js.

**Comment by wparad** [comment]
You do this the same as you would add an event any other way. I think this guide should help:, let me know if it doesn't https://www.javascripttutorial.net/dom/events/add-an-event-handler/

**Comment by satyam-bala** [comment]
Have tried all those, unfortunately, nothing worked :(

**Comment by wparad** [comment]
Can you share you exact code that didn't work? I want to make sure we aren't missing something obvious.

**Comment by satyam-bala** [comment]
test.html
----------
```
<!doctype html>
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="js/openapi-explorer.min.js"></script>
    <script src="js/test.js"> </script>
  </head>
  <body>
    <div class="content">
        <openapi-explorer spec-url="/v3/api-docs/users/"></openapi-explorer>
    </div>
  </body>
</html>
```

test.js
-------
$(document).ready(function(){
    $(".btn-execute").on('click', function(event){
        console.log("#1 Authorization : Bearer " + localStorage.access_token);
        event.detail.request.headers.append('Authorization', `Bearer ${localStorage.access_token}`);
        console.log(event.detail.request.headers);
    });
});

**Comment by wparad** [comment]
There are two problems with that code, the name of the element is not `.btn-execute` it's `#openapi-explorer` and the name of the event isn't `click`, it's `request`.

**Comment by satyam-bala** [comment]
I would recommend to cover this example in your documentation.  it would have saved my 2 days time :(

anyhow, thank you.
