### ISSUE TITLE
How to get default styles applied to a vanilla js installation?

### ISSUE THREAD

**Issue by fiddlerpianist** [Rhosys/openapi-explorer#114]
When I do the quickstart for "vanilla js," it looks as though absolutely zero styles are being loaded. Is this by design?

Here is what part of my Chrome window looks like with the quick-start code:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/5559537/205182978-da112ee1-4d57-4ec3-bd62-35e3497b1399.png">

Is there a way to at least minimally apply some kind of theme to an otherwise themeless installation?

**Comment by wparad** [comment]
There's a huge number of configuration options available in the docs, as well as tons of css-parts for further styling. Maybe if you could give an example of what you are trying to do, I can make some suggestions.

**Comment by fiddlerpianist** [comment]
I would just like an out-of-the-box,
I'm-not-a-frontend-guy-and-just-want-this-to-not-so-default-browsery option
that doesn't look ugly. :)

**Comment by fiddlerpianist** [comment]
For starters, could the default vanilla JS use the fonts defined in `main.css`? The way it looks right now, it uses zero CSS definitions for anything.

**Comment by wparad** [comment]
This is a web component, which means it is generated in a shadow dom, styles in your css won't automatically cascade into the components here, unless you explicitly make them. It's easy to do this though, all the html tags in this library have a css part, there are direct properties, and you can of course inject in css directly to the shadow dom.

The instructions for doing this are available in this documentation: [Styling OpenAPI Explorer](https://github.com/Rhosys/openapi-explorer/blob/release/0.10/docs/styling.md)

For color overrides you'll want to set the appropriate attributes: [coloring OpenAPI Explorer](https://github.com/Rhosys/openapi-explorer/blob/release/0.10/docs/documentation.md#colors)

No part of this requires VueJS or React. Additionally if you get stuck on overriding the styles for a component, please just add a message here whichever one you are stuck on and someone can make a recommendation on how to do it.

Since this is all available, i'm going to close this ticket but don't let that stop you from adding addition messages here.

**Comment by fiddlerpianist** [comment]
I don't understand how to use the stylesheets that are defined in the
main.css file in your repo, and I don't see any examples on how to do that
in the documentation. The default browser fonts do not look good. I would
also like the code examples to use a monospace font.

Can you explain how to do this specific thing?

**Comment by wparad** [comment]
What do you mean by "use the stylesheets that are defined in the main.css file"?

If you want to change the font there are two fonts variables used in different ways, you can set either or both by adding this style element to your html:
```html
<style>
      openapi-explorer {
        --font-regular: monospace;
        --font-mono: monospace; 
      }
</style>
```

**Comment by fiddlerpianist** [comment]
Thanks, I'll give that a try.

By `main.css` I meant: https://github.com/Rhosys/openapi-explorer/commit/3414b670f0ee0ba42281dc6690a599bb0bf009e7#diff-dc04fe78fcd14e40d5bfc012e5306a7c488f304d19ed4fb346ebc3c4f1a12a96 but it appears that you have just deleted it. So maybe that was adding to my confusion.

Just so I understand... if these two font variables aren't defined, it will just use the browser default for both (in my case, Times)? Could you point me in the direction of the font you used on the README.md for the screenshot? That one looks nice. (I'm not a designer and don't have much creativity when it comes to theming, so I'd love something to just "look nice" out of the box when I include the quick start code. Default browser fonts almost never look nice).

By the way, I am super impressed with the capabilities of the project and the clarity of the documentation layout, particularly around what I've seen for OpenAPI 3.1. Thanks for all of the hard work!

**Comment by wparad** [comment]
> By main.css I meant: https://github.com/Rhosys/openapi-explorer/commit/3414b670f0ee0ba42281dc6690a599bb0bf009e7#diff-dc04fe78fcd14e40d5bfc012e5306a7c488f304d19ed4fb346ebc3c4f1a12a96 but it appears that you have just deleted it. So maybe that was adding to my confusion.

Yeah sorry about that, I didn't realize there was something like that still in the repo.

>  it will just use the browser default for both (in my case, Times)? Could you point me in the direction of the font you used on the README.md for the screenshot? That one looks nice. (I'm not a designer and don't have much creativity when it comes to theming, so I'd love something to just "look nice" out of the box when I include the quick start code. Default browser fonts almost never look nice).

It will actually use your site default, with a fallback to the browser if not specified. That screen shot was taken from: https://authress.io/app/#/api?route=overview which uses `Lato, sans-serif`, we didn't define `--font-regular` so it automatically falls back to that. Does that make sense?

You can add it that to your site by throwing this in:
```html
<head>
  <link href="https://fonts.googleapis.com/css?family=Lato:200,300,400,500,600,700&display=swap" rel="stylesheet" crossorigin="anonymous">
</head>
<style>
  body {
    font-family: Lato, sans-serif;
  }
</style>


> By the way, I am super impressed with the capabilities of the project and the clarity of the documentation that it produces against my OpenAPI file. Thanks for all of the hard work!

Awesome glad to hear it.

**Comment by fiddlerpianist** [comment]
> It will actually use your site default, with a fallback to the browser if not specified. That screen shot was taken from: https://authress.io/app/#/api?route=overview which uses `Lato, sans-serif`, we didn't define `--font-regular` so it automatically falls back to that. Does that make sense?

Yes. I have something going now and am starting to customize. Thanks again for the help!
