### ISSUE TITLE
Scrolling is not working when the list of APIs beyond the screen

### ISSUE THREAD

**Issue by satyam-bala** [Rhosys/openapi-explorer#124]
Vertical Scrolling is not working when the list of APIs beyond the screen.

**Comment by wparad** [comment]
Can you provide a minimum reproduction of this issueo we can investigate?

**Comment by satyam-bala** [comment]
Sorry, i was happening only when I add additional div for Header with "overflow".   May be we can close this issue.

**Comment by wparad** [comment]
Awesome glad to hear it 👍
