### ISSUE TITLE
Custom route slot function?

### ISSUE THREAD

**Issue by gitblit** [Rhosys/openapi-explorer#128]
First off, this is a great openapi viewer! Well done!

I am looking to customize the displayed html in the route slot based on custom content in my swagger specs. My use case is almost identical to this example - I am trying to show permissions requirements:

https://github.com/Rhosys/openapi-explorer/blob/4c2aaea38082ef17130d78191c6ba8f05e15f2b6/docs/authress-example.vue#L74

I don't want to declare html slot overrides ahead of time, like this example. I think I want to define a component function that fills the slot after being provided the endpoint's spec data.

Is this reasonable?
Is there an alternative I should consider?

**Comment by wparad** [comment]
Maybe? I'm not really sure, would it be possible share more about what you are trying to do exactly? With this additional context it might be possible for us to come up with viable alternatives.

**Comment by gitblit** [comment]
Sure.

For each of my endpoints there is a custom spec extension that looks like this:
```json
"x-vas-claims": [
  "Company:Read", "Require:VendorIntegration"
]
```

These values vary with each endpoint. I'd like to show a pill/badge for each one, varying their style based on the particular value. I have been injecting them dynamically in the description for swagger-ui, but this may be an opportunity to improve this from flat text. The badges in your example inspired me.

**Comment by wparad** [comment]
If there is a way to do this with custom elements (the technology driving this library), I haven't been able to figure it out. Unlike React and Vue which allow you to inject in parameters into a slot, I'm not aware of a great solution. There are two options I can think of:

### 1. Use Scopes
I don't remember what the `scope` support is for this library, but your "claims" look like scopes, I don't know if your claims are really supposed to be scopes, because if they are, then updating your spec to use the scopes, would provide some default display of the scopes, which we could extend to display in a way which you would like.

### 2. Add a new slot
We can replace the `<slot name="${path.elementId}"></slot>` with
```html
<slot name="${path.elementId}"></slot>
<slot name="path-details"></slot>
```
or
```html
<slot name="${path.elementId}"><slot name="path-details"></slot></slot>
```

You then can dynamically control the slot by using the bound `explorerLocation`.

Thoughts?

**Comment by wparad** [comment]
Okay, I think this might work for you, what you want to probably do is dynamically generate your slot overrides. (Don't know what slots are? They are dynamic html elements that you insert yourself. That's how we are doing it in the Authress Badge scenario.) However in this case, we'll use your framework to dynamically create those as well.

For instance, we use vue so our solution would look like this:
```vue
<openapi-explorer>
  <div v-for="route of ['get-/v1/users/-userId-', 'delete-/v1/users/-userId-']" :key="route" :slot="route">
    <b-badge variant="outline-primary">{{ route }}</b-badge>
  </div>
</openapi-explorer>
```

But if you are using svelte, then you probably want:
```svelte
<openapi-explorer>
    {#each routes as route}
        <div slot="{route.method}-{route.path.replace(/[\s#:?&={}]/g, '-')}">
            <b-badge variant="outline-primary">{route.description}</b-badge>
        </div>
    {/each}
</openapi-explorer>
```

Hope that helps, I'm assuming this will solve your particular challenge, let me know if that enables us to close this issue.

**Comment by gitblit** [comment]
That looks like it would work great if I had the spec object graph in memory when I declare the `openapi-explorer` fragment. Currently I am setting the specification URL and letting the library fetch it. I'm going to see if I can make your approach work.

**Comment by wparad** [comment]
"Are the slots reactive" that's a question I have not asked myself, but if they are you can get the spec object graph by listening for the `@spec-loaded` event and pull it out from there, and then dynamically updating the `routes` array in the above example.

**Comment by gitblit** [comment]
Ooooh. Interesting. I will give that a try too.

**Comment by wparad** [comment]
I'll assume this worked out, closing for now.

**Comment by gitblit** [comment]
I gave both ideas a go today.

- Scopes. Our authorization is `bearer`, not `oauth2`. According to the Swagger spec, you are not allowed to define scopes on non-oauth2 security definitions and I confirm the attempt makes swagger-editor very unhappy. I think that's why I used custom extensions.
- Unfortunately, it looks like the Svelte compiler is not a fan of dynamic slots. This clever proposal triggers an explicit compile error. ![image](https://user-images.githubusercontent.com/868217/220936598-fa926c45-a780-4f02-9e5c-8ec81bcf09c9.png)

**Comment by wparad** [comment]
I see it's been a long running request in Svelte :( https://github.com/sveltejs/svelte/issues/3480

Re the scopes, this is what the specification has to say about it:
> Each name MUST correspond to a security scheme which is declared in the [Security Schemes](https://spec.openapis.org/oas/v3.1.0#componentsSecuritySchemes) under the [Components Object](https://spec.openapis.org/oas/v3.1.0#componentsObject). If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution, and the list MAY be empty if authorization does not require a specified scope. For other security scheme types, the array MAY contain a list of role names which are required for the execution, but are not otherwise defined or exchanged in-band.

https://spec.openapis.org/oas/v3.1.0#security-requirement-object

So in fact specifying these are totally allowed. And irrespective of what other tools you are using, supporting this in a better way in this library, is something we can absolutely do.

However if that's isn't something you are interested in going with, I can understand that. I'm going to see if it is possible to provide an alternative.

**Comment by gitblit** [comment]
This cool usage of roles was added to 3.1. But it looks like OpenAPI 3.1 is generally problematic for the ecosystem. swagger-ui just added support for it 3 weeks ago, 2 years after the spec was released. It looks like ReDoc supports 3.1. My microservices that dynamically generate the Swagger specs currently do not - Swashbuckle & FastAPI - and it looks like they've been waiting for swagger-ui to support it.

I can try to generate deliberately invalid specs from my microservices and maybe I can disable validation so the existing swagger-uis won't break, and then maybe apiexplorer will show the roles on an 3.0 specification?

**Comment by gitblit** [comment]
That sounds promising.

Would there be any benefit to pushing the Operation object in that event rather than the coordinates for the Operation object?

**Comment by wparad** [comment]
> That sounds promising.
> 
> Would there be any benefit to pushing the Operation object in that event rather than the coordinates for the Operation object?

We could pass back out the whole Operation I guess. I'm trying to think about whether or not there is stuff in there that is internal. Is there something specific you would want to utilize?

**Comment by gitblit** [comment]
It may not be necessary.... I just need to know how to retrieve the operation, if not pushed, because it contains my array of claims.

**Comment by wparad** [comment]
I went back and forth on this, I'm adding the whole operation in.

**Comment by gitblit** [comment]
This approach works perfectly! 👏
