### ISSUE TITLE
Enabling null display is additive on query parameters

### ISSUE THREAD

**Issue by gitblit** [Rhosys/openapi-explorer#129]
Checkout this screen capture.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/868217/218289169-94df492f-cc95-4c02-8943-b90c420c750a.png">

I am navigating back & forth between two endpoints. Each time I do another `|null` is appended to the parameter type.

**Comment by wparad** [comment]
Do you have an minimal example that is able to replicate this functionality. I'm assuming it is related to the schema-utils.js

```js
if (dataType.includes('┃null') && schema.format) {
      schema.format += '┃null';
    }
```

which is updating the schema which it should not be doing, we probably need a new variable there that doesn't get mucked with, but we can validate this once we have a repro. (if you are up for fixing it, feel free to do so as well)

**Comment by gitblit** [comment]
Your fix works great! 👏
