### ISSUE TITLE
Server Side rendering with Nuxt

### ISSUE THREAD

**Issue by iasisalomon** [Rhosys/openapi-explorer#13]
When I import openapi-explorer as a Vue Plugin [Docs](https://nuxtjs.org/docs/2.x/directory-structure/plugins/), it freezes with the following error.

![Screenshot from 2021-04-20 12-09-55](https://user-images.githubusercontent.com/48367845/115420236-5b7baa00-a1d1-11eb-8e9b-17937b4e8f9c.png)

Any ideas?

**Comment by wparad** [comment]
So it isn't a plugin, so I'm not surprised that it's causing a problem like that. Is there a reason it's being imported that way instead of just importing as you would with any other internal component?

**Comment by iasisalomon** [comment]
With `import 'openapi-explorer';` on the component only, nuxt shows the same error and also freezes.

**Comment by wparad** [comment]
I'm going to try to look into if we can expose an non-minified version to see if that can help, in the meantime, if you can share a minimal reproduction, that would definitely help us to investigate what might be going on.

**Comment by iasisalomon** [comment]
Found this error and had no luck on solving it.
`Module build failed (from ./node_modules/babel-loader/lib/index.js):                                                                                                                     friendly-errors 10:24:01
TypeError:/src/.nuxt/client.js: this.setDynamic is not a function`

**Comment by wparad** [comment]
Do you have a reproduction example that we can use to look into the problem you are seeing. From [this result](https://github.com/babel/babel-loader/issues/560) Babel suggests the issue is mismatch in the babel config and dependencies.

**Comment by iasisalomon** [comment]
Uninstalled all babel plugin, and discovered  "presets: ['vue-app']" is the module causing trouble.

**Comment by wparad** [comment]
> Cannot find module '@skatejs/ssr/register'

I didn't have any trouble with `npm install @skatejs/ssr`, are you running into something different?

**Comment by iasisalomon** [comment]
Installed the dependency and returned to the starting point with the self issue.
We are trying to include openapi-explorer as a component on this nuxt template.
[Mithech Nuxt Template](https://themeforest.net/item/mitech-vue-nuxt-js-technology-blog-template/26837132)
Will keep you updated.

**Comment by wparad** [comment]
Okay I figured out the best way without any complicated tricks here, it looks like some of these packages aren't supported anymore and nuxt doesn't do this vanilla straight out of the box. So here's a working solution:

In the vue component add explorer to be rendered on the client side:
```vue
<template>
  <div class="container">
    <client-only>
      <openapi-explorer spec-url="https://petstore.swagger.io/v2/swagger.json"></openapi-explorer>
    </client-only>
  </div>
</template>

<script>
export default {
  created () {
    if (process.client) {
      require('openapi-explorer')
    }
  }
}
</script>
```

**Comment by iasisalomon** [comment]
Thanks a lot. It's working perfectly. Hope that we can show you the final product soon.

**Comment by wparad** [comment]
Awesome glad to hear it. :+1:
