### ISSUE TITLE
oneOf does not work with multipart/form-data

### ISSUE THREAD

**Issue by darcyrush** [Rhosys/openapi-explorer#132]
Currently, using `oneOf` within `multipart/form-data` does not display any of the schemas defined within. Removing the `oneOf` and keeping one schema will display its form fields in the generator. 

Below is a minimum reproducible example
```json
{
  "openapi": "3.1.0",
  "paths": {
    "/example": {
      "post": {
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "oneOf": [
                  {
                    "type": "object",
                    "properties": {
                      "prop1": {
                        "type": "string"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "properties": {
                      "prop2": {
                        "type": "number"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by wparad** [comment]
Seems like the spec supports it. Here's the part I don't get, how do your api clients know which payload is going to be returned. It seems like potentially a bad idea, right?

**Comment by darcyrush** [comment]
Do you mean in terms of an actual service trying to implement the openapi contract? Or do you mean clients implementing your library to display the payload of the oneOf schema definition?

If its the former, and if the response is consistent, it's not an issue; i.e. returning a string ID regardless of what is uploaded. If the response changes depending on the upload, then I believe you cannot use the above method and instead you must define each entire schema individually to contain both the upload and corresponding response.

If its the latter, I have seen other openapi explorers display radio buttons which let you toggle which schema within the `oneOf` you view at any time. They seem to use the description (when provided) of each nested schema.

**Comment by wparad** [comment]
The latter isn't a problem, there are ways in the library to handle this for other `oneOf`. I was curious about the former, but "it's consistent with the original request" makes sense. Although in that case (and in the one you've shared) would it make sense to use a compound type instead of `oneOf` or is this much more complicated with many different fields being different?

**Comment by darcyrush** [comment]
> or is this much more complicated with many different fields being different?

Yes this is my case. The upload form fields vary wildly but the response is always limited to the same success and failure responses.

**Comment by wparad** [comment]
This has been fixed in the latest version, you can see the linked PR: #133
