### ISSUE TITLE
SSR execute issues, automatic login credentials

### ISSUE THREAD

**Issue by iasisalomon** [Rhosys/openapi-explorer#14]
Hi there, we continue the implementation of the package.

We find that we we execute an API call, Nuxt automatically triggers 404 page. Any thoughts on why this is happening?

We use a Basic Auth, is there any way to set a demo user and password to be automatically set when a new user enters the reference?

**Comment by wparad** [comment]
> We find that we we execute an API call, Nuxt automatically triggers 404 page. Any thoughts on why this is happening?

Nothing that's explicitly being in this library, that I'm aware of. If you track down what the issue is we can try to adjust otherwise we'd need a full reproduction repo of what's going on to investigation.

As far as adding in credentials dynamically, definitely, you can modify requests however you like with the interceptors. Check out the documentation for how to do that: https://github.com/Rhosys/openapi-explorer/blob/release/0.3/docs/documentation.md

**Comment by iasisalomon** [comment]
Will investigate further, and post what happened.

**Comment by iasisalomon** [comment]
> As far as adding in credentials dynamically, definitely, you can modify requests however you like with the interceptors. Check out the documentation for how to do that: https://github.com/Rhosys/openapi-explorer/blob/release/0.3/docs/documentation.md#events

Regarding this approach, How should I set a Key? I'm lost on where the information from the login is stored.

![Screenshot from 2021-04-27 09-55-49](https://user-images.githubusercontent.com/48367845/116245065-ef53f580-a73e-11eb-84b4-d91157ab9f4a.png)

**Comment by wparad** [comment]
It depends on who is going to be setting the key. If your users are setting the key, then they would use the authentication section.

However, I understand that your users wouldn't be setting the key directly, you wanted a process to dynamically set the key from code. Is that correct?

If so, there's no direct way to set the key, instead we modify the request directly before sending it to the api. For every request, the `@request` method will fire.
`<openapi-explorer @request="requestInterceptor"> </openapi-explorer>`

```js
requestInterceptor(event) {
  Object.assign(event.detail.request.options.headers, { Authorization: `Bearer ${userToken}` });
}
````
And in here you can directly access the request `headers` object and set the key you want to be there.

**Comment by iasisalomon** [comment]
> If so, there's no direct way to set the key, instead we modify the request directly before sending it to the api. For every request, the @request method will fire.
> <openapi-explorer @request="requestInterceptor"> </openapi-explorer>

I am using this approach as a placeholder regarding Auth, and has been very useful for setting an id variable from a response into a request.
The functionality we seek is to set the a demo key from the code whenever any user enters the openapi docs, as an "on load" event. Then the user can change their Auth manually changing the key for one they may have.
The onload part is what I am lost about.

**Comment by wparad** [comment]
Okay, just released a new version which contains `setSecuritySchemeToken(securitySchemeId, token)` method to dynamically set the token. One way to do this would be:
```js
document.getElementsByTagName("openapi-explorer")[0].setSecuritySchemeToken('basicAuth', 'user:password');
```

**Comment by iasisalomon** [comment]
Great, thanks!

**Comment by iasisalomon** [comment]
I tried adding the code in the last lifecycle hook of nuxt 
`	mounted() {
		document.getElementsByTagName('openapi-explorer')[0].setSecuritySchemeToken('basicAuth', 'demoApiUser:demo2019');
	},`

Still, it does not seem to find the element

`	mounted() {
		console.log(document.getElementsByTagName('openapi-explorer')[0]);
	},`
	
	`undefined`

**Comment by wparad** [comment]
> I tried adding the code in the last lifecycle hook of nuxt
> ` mounted() { document.getElementsByTagName('openapi-explorer')[0].setSecuritySchemeToken('basicAuth', 'demoApiUser:demo2019'); },`
> 
> Still, it does not seem to find the element
> 
> ` mounted() { console.log(document.getElementsByTagName('openapi-explorer')[0]); },`
> 
> ```
> `undefined`
> ```

It probably hasn't been loaded into DOM yet(?). You'll probably want to do a quick check that the `if(openapi-explorer)` is actually is in your DOM before attempting to call methods based on it. It's worth opening the dev tools and running this real quick on a loaded app for sanity:
`console.log(document.getElementsByTagName('openapi-explorer')[0]);`

![image](https://user-images.githubusercontent.com/5056218/116288245-9bbec780-a791-11eb-8589-96f97e51581b.png)

If for some reason your site is delaying the load of the `openapi-explorer`, you'll also want to wait for that process to be completed before calling methods on it.

**Comment by iasisalomon** [comment]
Having problems with this while compiling for production. It does not seem to recognize set Security Scheme tokens. 
```
f33fd07.js:3213 Uncaught (in promise) Error: SecuritySchemeNotFound
    at HTMLElement.setSecuritySchemeToken (f33fd07.js:3213)
    at f.onSpecLoaded (d9130c2.js:1)
    at ee (e37291c.js:2)
    at HTMLElement.n (e37291c.js:2)
    at HTMLElement.Rr.c._wrapper (e37291c.js:2)
    at HTMLElement.afterSpecParsedAndValidated (f33fd07.js:3213)
    at HTMLElement.loadSpec (f33fd07.js:3213)
    at async f33fd07.js:3213
```
```
        async setSecuritySchemeToken(e, t) {
            const r = this.resolvedSpec && this.resolvedSpec.securitySchemes.find((t=>t.apiKeyId === e));
            if (!r)
                throw Error("SecuritySchemeNotFound");
            let n = t.replace(/^(Bearer|Basic)\s+/i, "");
            r.type && "http" === r.type && r.scheme && "basic" === r.scheme.toLowerCase() ? n = `Basic ${btoa(n)}` : r.scheme && "bearer" === r.scheme.toLowerCase() && (n = `Bearer ${n}`),
            r.finalKeyValue = n,
            this.requestUpdate()
        }
```

**Comment by wparad** [comment]
@iasisalomon please include a minimal reproducible spec and the function parameters you are using to make your call that is triggering the error.

**Comment by iasisalomon** [comment]
sorry i did not send it earlier, I include additional info here.

```
        <openapi-explorer
          :spec-url="specUrl"
          :server-url="serverUrl"
          show-server-selection="false"
          show-overview="false"
          show-authentication="true"
          @response="responseInterceptor"
          @request="requestInterceptor"
          @spec-loaded="onSpecLoaded"
        >
          <div slot="overview">
            <IncludeContent slug="overview" />
          </div>
          <div slot="nav-section">Error Codes</div>
          <div slot="custom-section">
            <IncludeContent slug="error-codes" />
          </div>
        </openapi-explorer>
        ```

```
    onSpecLoaded(spec) {
      spec.detail.tags.forEach(tag => {
        tag.expanded = false;
      });
      // security scheme injection
      document
        .getElementsByTagName('openapi-explorer')[0]
        .setSecuritySchemeToken('basicAuth', 'demoApiUser:password');

      // css style injection
      const apiExplorer = document.getElementsByTagName('openapi-explorer')[0];
      const linkElem = document.createElement('link');
      linkElem.setAttribute('rel', 'stylesheet');
      linkElem.setAttribute('href', '/openapi/openapi.css');
      apiExplorer.shadowRoot.appendChild(linkElem);
    }
    ```

**Comment by wparad** [comment]
@iasisalomon please include a minimal reproducible spec

**Comment by iasisalomon** [comment]
The problem was we were not providing correctly the specUrl and serverUrl because of Nuxt env variables handling. Thanks for your quick response.

**Comment by gitblit** [comment]
I am trying to achieve the same result with Svelte & SvelteKit. I have openapi-explorer working but I can't use the `@spec-loaded` syntax. The Svelte compiler complains. Is there an alternative?

<img width="669" alt="image" src="https://user-images.githubusercontent.com/868217/218227127-99383432-a5d5-4354-9133-bfe728369496.png">

**Comment by wparad** [comment]
> I am trying to achieve the same result with Svelte & SvelteKit. I have openapi-explorer working but I can't use the `@spec-loaded` syntax. The Svelte compiler complains. Is there an alternative?
> 
> <img alt="image" width="669" src="https://user-images.githubusercontent.com/868217/218227127-99383432-a5d5-4354-9133-bfe728369496.png">

It's an event, so you'll want to review how to attach event listeners. The first result on Google immediately shows how this is possible:
https://svelte.dev/repl/78e0855b596e4a1391d77ad2d9e8dc8a?version=3.35.0

Here is there example using the `click` event. You can easily adjust it for this `spec-loaded` event:

```html
<script>
	function onClick(event) {
		
	}
</script>

<h1 on:click|preventDefault|stopPropagation|capture|nonpassive={onClick}>Event listeners</h1>

<div on:click|self={() => console.log('parent')}>
	parent
	<div on:click={() => {console.log('child')}}>
		child
	</div>
</div>
```

**Comment by gitblit** [comment]
@wparad thank you so much for the clue that `@` and `on:` are related. I am not very strong in JS/browser coding and that was just what I needed!
