### ISSUE TITLE
Only show "Required Scopes" if there are any

### ISSUE THREAD

**Issue by gitblit** [Rhosys/openapi-explorer#140]
Super minor cosmetic issue. Endpoints guarded by a bearer security definition include references to `Required scopes` even if none are defined. Maybe only show this if there are required scopes?

![image](https://user-images.githubusercontent.com/868217/221286557-6eb50c70-7e07-47e3-9167-f1563834a2ea.png)

**Comment by wparad** [comment]
So what's weird is that this is the code:
```js
function getOauthScopeTemplate(scopes) {
  if (!scopes || !scopes.length || !Array.isArray(scopes)) {
    return '';
  }

  return html`
    <div>
      <b>Required scopes:</b> 
      <br/> 
      <div style="margin-left:8px">  
        ${scopes.map(scope => html`<span>${scope}</span>&nbsp;`)}
      </div>  
    </div>`;
}
```

We can filter out null objects or `empty` objects from the list. Is there something in there that shouldn't be? Do you have a sample spec?

**Comment by gitblit** [comment]
Those are really good defensive checks. I think the issue is my spec is generated by Swashbuckle with scopes like this:

```json
"security": [
  {
    "Bearer": [
      null
    ]
  }
],
```

This is a faulty spec. Not sure if you want to handle it.

**Comment by wparad** [comment]
We'll just handle it, add more defensive capabilities is always the right call ;)
