### ISSUE TITLE
why skipExampleStrings set true in api-request.js

### ISSUE THREAD

**Issue by Liwenju** [Rhosys/openapi-explorer#147]
https://github.com/Rhosys/openapi-explorer/blob/2f3836ff13434525b3ae219dfb947cd284c25e30/src/components/api-request.js#L345

![image](https://user-images.githubusercontent.com/14797520/231731601-d90ef84b-7690-4c3f-a95a-94a54d89c607.png)

hello, May I inquire as to why the generation of examples for string types is omitted in api-request.js? thanks

**Comment by wparad** [comment]
@Liwenju is this an issue or is everything okay now?

**Comment by Liwenju** [comment]
> 
in  schema-utils.js file, function getSampleValueByType
has this code: 
...
  if (skipExampleStrings && typeof example === 'string') { return ''; }
...
I can't understand...  why not  replace `typeof example === 'string' ` to `example === 'string'`

![image](https://user-images.githubusercontent.com/14797520/231736776-c87138c0-df9a-4699-95f8-a771be0e601e.png)

**Comment by wparad** [comment]
I thought the code is pretty straightforward. if the type of the example is a string then don't return it. Is this a problem, if so can you please share a minimum example along with what your expectation for the display should be. That would help us debug any potential issues with code.

Thanks,
Warren

**Comment by Liwenju** [comment]
> I thought the code is pretty straightforward. if the type of the example is a string then don't return it. Is this a problem, if so can you please share a minimum example along with what your expectation for the display should be. That would help us debug any potential issues with code.
> 
> Thanks, Warren

if is `typeof example === 'string'` , when schema has example, eg:
![image](https://user-images.githubusercontent.com/14797520/231762352-27e3055b-d615-417f-9f02-ff5b899e982e.png)

will render as 

![image](https://user-images.githubusercontent.com/14797520/231762798-ceabfe7b-ccc1-4d69-ae72-79c28b091a0d.png)


but i want to render 
![image](https://user-images.githubusercontent.com/14797520/231762672-3526e7b4-3782-4bb7-a363-160407b8c10a.png)


and swagger-ui also render  when the type of the example is a string

**Comment by wparad** [comment]
Ah I see. The reason that doesn't show is because we've had concerns that it would be used to generate actual calls to your API with values that don't necessarily make sense.

In otherwards think of the "BODY" section as actually being used by the user to call the API, it isn't an example. You likely don't want that string sent. However, we are thinking about adding an examples section. If we were to add that, would you be interested in it?

**Comment by wparad** [comment]
Closing this in favor of extended example displays.
