### ISSUE TITLE
Enable setting the "Max expansion depth" for a model

### ISSUE THREAD

**Issue by zorrobiwan** [Rhosys/openapi-explorer#148]
I would like to get 

![image](https://user-images.githubusercontent.com/2226019/233950984-ed3aa86b-31ce-4f6d-afbb-811d7c19a95f.png)

instead of 

![image](https://user-images.githubusercontent.com/2226019/233950879-3f312b07-0162-4726-bceb-5d9c76424e4b.png)

which is the default behavior

How can I do ?

Thx

**Comment by wparad** [comment]
Do you mean clicking on the litter triangles? It isn't clear what you would like to have, would you be able to add more context?

**Comment by zorrobiwan** [comment]
Thx for the last reply.

I would like to get a view with all the items collapsed by default (like if you clic on all the small triangles yes).

By default all the items are expanded

**Comment by zorrobiwan** [comment]
thx for the reply too ... so no direct solution ?

**Comment by wparad** [comment]
Not at the moment, I think there is some handling built in for setting the default visible depth, but it will have to be reviewed before publicly documented.

**Comment by zorrobiwan** [comment]
Great !
Thank you

**Comment by wparad** [comment]
Actually I just saw that maybe we have something undocumented, would you be willing to try out to see if adding the attribute `schema-expand-level="1"` solves this for you?

**Comment by zorrobiwan** [comment]
So simple :)
Yes, it's working well.
Thx !!
