### ISSUE TITLE
OAuth doesn't seem to work out of the box

### ISSUE THREAD

**Issue by accountForIssues** [Rhosys/openapi-explorer#149]
I am not a frontend developer so maybe I'm missing something.

But I simply used the raw html example with our OpenAPI json.

It loads fine, I enter the "Client ID" -> Redirect to our Auth0 login -> Log in success -> Redirected back to `https://api.domain.tld/docs.html#access_token=xxxxxxxxxxxxxxxx&scope=access%3Ausers&expires_in=7200&token_type=Bearer&state=xxxxxxxxx?route=auth` (I can see that url in the address bar)

Nothing changes. API token is not set. Refreshing or trying again doesn't work.

Is there anything else I can do ? I'd love to replace our docs with this one.

EDIT: The redirect url is in Auth0 callback list and the access token received is valid (checked on jwt.io)

There are also no errors in the console or on the page.

**Comment by wparad** [comment]
That's because Auth0 is incorrectly putting the access token and other properties in the hash, you can see we would actually have to set the `responseMode` property to `query` for this to work out of the box: https://auth0.com/docs/libraries/auth0js#available-parameters. I don't know why Auth0 took this confusing approach, where all the other auth providers seem to do this more reasonably. I believe that is likely because you are using the **implicit** auth flow, which is has long been deprecated due to security reasons. If you were to switch your oauth2 flow configuration in your openapi spec to be `authorizationCode` instead, I would expect this to work out of the box.

**Comment by accountForIssues** [comment]
We currently use Swagger UI (with FastAPI) that had implicit as the default. Both implicit and authCode flow work fine on it.

**Comment by wparad** [comment]
So it looks like the current version doesn't actually do the exchange automatically, it requires a method, call. I'm pushing out a new version that should automatically execute the code exchange on page load. I don't know if it will fix the issue you are seeing (without the minimal repro), but as soon as github stops having an outage, it will be release in the `1.0` version.

**Comment by accountForIssues** [comment]
@wparad Thanks for the quick fix. Indeed, I can see a call to /token however the client_id seems to empty in request data leading to a 401.

```
grant_type	"authorization_code"
redirect_uri	"https://api.domain.tld/docs.html#?route=auth"
code	"xxxxxxxxxxxxx"
client_id	""
code_verifier	"00000"
```

I'll see if I provide a spec for you to test.

**Comment by accountForIssues** [comment]
Hi, I've solved the issue. I didn't submit a PR as it's a bit hacky and I'm sure you could do it much more gracefully.

Anyways, there were two issues:

1. empty `clientId` - I saved the `clientId` to `localStorage` and delete it post login.
2. It could be that Auth0 has changed but they seem to expect a different `code_verifier` format. After adding the `clientId`, I got the error: `Parameter 'code_verifier' must be between 43 and 128 characters long`

For 2, looking at Auth0 docs, they use `crypto` module to generate 32 random bytes, encode to base64 and use that as `code_verifier`. I found a gist that did the same using `window.crypto`, so tried that and it worked.

```diff
diff --git a/src/templates/security-scheme-template.js b/src/templates/security-scheme-template.js
index e746abc..d670d84 100644
--- a/src/templates/security-scheme-template.js
+++ b/src/templates/security-scheme-template.js
@@ -55,6 +55,17 @@ async function fetchAccessToken(tokenUrl, clientId, clientSecret, redirectUrl, g
   const urlFormParams = new URLSearchParams();
   const headers = new Headers();
   urlFormParams.append('grant_type', grantType);
+  if (!clientId) {
+    const client_id = localStorage.getItem("clientId")
+    if (client_id) {
+      localStorage.removeItem("clientId")
+      clientId = client_id
+    }
+    else{
+      console.error("client id not found")
+      return
+    }
+  }
   if (redirectUrl) {
     urlFormParams.append('redirect_uri', redirectUrl);
   }
@@ -175,6 +186,7 @@ export async function checkForAuthToken(redirectToApiLocation) {
 async function onInvokeOAuthFlow(apiKeyId, flowType, authUrl, tokenUrl, e) {
   const authFlowDivEl = e.target.closest('.oauth-flow');
   const clientId = authFlowDivEl.querySelector('.oauth-client-id') ? authFlowDivEl.querySelector('.oauth-client-id').value.trim() : '';
+  localStorage.setItem("clientId", clientId)
   const clientSecret = authFlowDivEl.querySelector('.oauth-client-secret') ? authFlowDivEl.querySelector('.oauth-client-secret').value.trim() : '';
   const sendClientSecretIn = authFlowDivEl.querySelector('.oauth-send-client-secret-in') ? authFlowDivEl.querySelector('.oauth-send-client-secret-in').value.trim() : 'header';
 
@@ -191,12 +203,24 @@ async function onInvokeOAuthFlow(apiKeyId, flowType, authUrl, tokenUrl, e) {
     const authUrlObj = new URL(authUrl);
     const authCodeParams = new URLSearchParams(authUrlObj.search);
     if (flowType === 'authorizationCode') {
-      const randomBytes = new Uint32Array(3);
-      (window.crypto || window.msCrypto).getRandomValues(randomBytes);
+      // const randomBytes = new Uint32Array(3);
+      // (window.crypto || window.msCrypto).getRandomValues(randomBytes);
+      // from https://gist.github.com/CMCDragonkai/bcfdf2a40b520e92180aec3371d14e46
+      let size = 32
+      const randomBytes = Buffer.allocUnsafe(size);
+      let i = 0;
+      while (size > 0) {
+        const chunkSize = Math.min(size, 65536);
+        const chunk = randomBytes.subarray(i, chunkSize);
+        (window.crypto || window.msCrypto).getRandomValues(chunk);
+        i += chunkSize;
+        size -= chunkSize;
+      }
       authCodeParams.set('nonce', randomBytes.toString('hex').split(',').join(''));
       grantType = 'authorization_code';
       responseType = 'code';
-      const codeVerifier = randomBytes.toString('hex').split(',').join('');
+      // from https://auth0.com/docs/get-started/authentication-and-authorization-flow/call-your-api-using-the-authorization-code-flow-with-pkce#javascript-sample
+      const codeVerifier = randomBytes.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
       const hash = await (window.crypto || window.msCrypto).subtle.digest('SHA-256', new TextEncoder().encode(codeVerifier));
       const codeChallenge = base64url(hash);
 ```

**Comment by wparad** [comment]
Okay, thanks for finding those issues. As you pointed out, we'll have to find better ways. We shouldn't need the clientId saved, as it should already be available in memory. And we can't use Buffer, because it doesn't exist in browsers. But I'll reopen this and we can take it from there.

**Comment by wparad** [comment]
Okay, there is a new version out, `1.0.538` I don't know if it will work with auth0 weird requirements, but it works with our test account (in Authress). If you find additional problems, please keep them coming.

**Comment by accountForIssues** [comment]
It works well now. Auth0 docs are not the best out there so I guess it was a matter of the length of the code being shorter than they expected.

Thanks for the quick fixes.
