### ISSUE TITLE
Parameter description is not being shown

### ISSUE THREAD

**Issue by accountForIssues** [Rhosys/openapi-explorer#155]
Referring to attached image, the title/description is absent for one of the models parameters and the title is absent from the previous one.

I've attached the affected schema `openapi.json.txt` as well.

The docs are auto-generated by FastAPI and everything works fine on Swagger.

![image](https://github.com/Rhosys/openapi-explorer/assets/52367365/981b1f32-c0a9-4d9e-b2a8-e0b0d7eb9aaa)
[openapi.json.txt](https://github.com/Rhosys/openapi-explorer/files/11565852/openapi.json.txt)

**Comment by wparad** [comment]
Fixed in #156
