### ISSUE TITLE
API key is not saved sometimes and causes a redirection

### ISSUE THREAD

**Issue by accountForIssues** [Rhosys/openapi-explorer#158]
Example schema
```json
{
    "openapi": "3.0.2",
    "info": {
        "title": "API access"
    },
    "paths": {
        "/api/credits/": {
            "get": {
                "tags": [
                    "account"
                ],
                "summary": "Retrieve Remaining Credits",
                "description": "Credits in the user account.",
                "operationId": "retrieve_remaining_credits_api_credits__get",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    }
                },
                "security": [
                    {
                        "APIKeyHeader": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "APIKeyHeader": {
                "type": "apiKey",
                "in": "header",
                "name": "X-API-Key"
            }
        }
    }
}
```

index.html used to test

```html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <script type="module" src="https://unpkg.com/openapi-explorer/dist/browser/openapi-explorer.min.js"></script>
</head>

<body>
  <openapi-explorer default-schema-tab="model" collapse nav-item-spacing="relaxed" show-server-selection="false"
    spec-url="openapi.json">
  </openapi-explorer>
</body>

</html>
```

To reproduce:

Running a local python server with `python -m http.server 8000`
- visit http://localhost:8000
- click on auth, now the url is http://localhost:8000/#?route=auth
- (optional) enter any value in api key
- click on set, the API key is quickly applied before there is a redirection and it is gone. Now the url is http://localhost:8000/?#?route=auth
- At this stage, everything works and there are no more redirection. It mainly happens on first visit.

Is it a bug or can something be done in html ?

[Screencast from 2023-06-08 23-17-57.webm](https://github.com/Rhosys/openapi-explorer/assets/52367365/b7a84d70-2857-420b-8530-a41fa5002e51)

**Comment by wparad** [comment]
Well that definitely doesn't need a redirect there, so that shouldn't be happening. This is a bug.

**Comment by wparad** [comment]
I think wee found the problem and it should be fixed with https://github.com/Rhosys/openapi-explorer/commit/f054e5fafe48563913419633af46f8edbe92d5ba which will be released automatically shortly.
