### ISSUE TITLE
HTML Injection (Replace Overview content)

### ISSUE THREAD

**Issue by iasisalomon** [Rhosys/openapi-explorer#16]
We want to preserve Overview tag, but to inject an HTML page instead of specifying the content on the swagger.json file. This is to avoid the json file to overspecify stuff.

Is there any way to do this?

**Comment by wparad** [comment]
There's a named slot `overview`, usable in vue like:
```
<openapi-explorer>
  <div slot="overview">
    New overview info
  </div>
</openapi-explorer>
```

I'm assuming that works for you case.

**Comment by iasisalomon** [comment]
Great, read about it in the docs but was unsure if the tab would dissapear. Thanks!
