### ISSUE TITLE
Support for Legacy Swagger v2.0

### ISSUE THREAD

**Issue by kaiyoma** [Rhosys/openapi-explorer#161]
I'm investigating openapi-explorer as an alternative to swagger-ui, and it's mostly working, except all parameters are missing. For example, here's what swagger-ui renders for one of our GET actions:

![image](https://github.com/Rhosys/openapi-explorer/assets/10719780/90f39360-7b94-45d4-8f6f-2d8302aeb515)

And here's what openapi-explorer renders for the same URL and action:

![image](https://github.com/Rhosys/openapi-explorer/assets/10719780/92297359-3663-4d30-8136-ef07f36c342f)

I've looked through the config options and nothing is jumping out at me. Shouldn't the parameters "just work"? They're missing for every action.

**Comment by kaiyoma** [comment]
Here's a bit more info. In the JSON spec file, the action mentioned above is defined like this:

```
    "/audit/exportLogs.do": {
      "$ref": "/web/api/api_json/audit.json#/paths/~1audit~1exportLogs.do"
    },
```

If I open that other file (`audit.json`), I see this:

```
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0"
  },
  "basePath": "/cvpservice",
  "paths": {
    "/audit/exportLogs.do": {
      "get": {
        "produces": ["application/json", "application/x-www-form-urlencoded"],
        "parameters": [
          {
            "description": "startTime",
            "in": "query",
            "name": "startTime",
            "required": true,
            "type": "string"
          },
          {
            "description": "endTime",
            "in": "query",
            "name": "endTime",
            "required": true,
            "type": "string"
          },
          {
            "description": "category",
            "in": "query",
            "name": "category",
            "required": true,
            "type": "string"
          },
          {
            "description": "objectKey",
            "in": "query",
            "name": "objectKey",
            "required": true,
            "type": "string"
          }
        ],
        ...
```

**Comment by kaiyoma** [comment]
Here's another interesting data point: if I use the advanced search to search for `startTime` in only the request parameters, it seems to find it:

![image](https://github.com/Rhosys/openapi-explorer/assets/10719780/928aec47-da15-4a99-988e-09c368313b5e)

So openapi-explorer does "know" about this parameter, but why isn't it rendering it?

**Comment by wparad** [comment]
The reason this isn't rendering is because largely the swagger v2.0 has be obsolete for quite some time in favor of the standardize OpenAPI specification (which is v3.0). Anything that happens to "work" in here is largely accidental and is because it coincides with how the v3.0 is.

We have a couple of options here, but the best one is going to be to try to upgrade your spec to be v3.0 compatible. There are a bunch of tools to do this, after a couple of seconds of googling I found this one: https://mermade.org.uk/openapi-converter

So the question is, do you have the option to run an upgrade on your spec to make it compliant with the current standard?

**Comment by kaiyoma** [comment]
Ah okay, I was kind of wondering if our spec was old. Thanks for confirming! Let me talk to our backend devs and see if we can publish a newer version of our spec.

**Comment by wparad** [comment]
> Ah okay, I was kind of wondering if our spec was old. Thanks for confirming! Let me talk to our backend devs and see if we can publish a newer version of our spec.

If not, we can see what alternatives are available. Just as an example, you also don't need to change everything, but if you are in control of the generation/management of the spec, a simple thing like wrapping the `type` in a `schema` solves this:

```json
"parameters": [
    {
        "description": "startTime",
        "in": "query",
        "name": "startTime",
        "required": true,
        "schema": {           
            "type": "string"
        }
    }
]
```

**Comment by kaiyoma** [comment]
Sounds good, I'll investigate that too. Feel free to close this issue.
