### ISSUE TITLE
rounding errors when copying integers that exceed the maximum precision on the page

### ISSUE THREAD

**Issue by Liwenju** [Rhosys/openapi-explorer#165]
When copying a  large numbers  on a page, rounding errors will occur

Location:https://github.com/Rhosys/openapi-explorer/blob/main/src/utils/common-utils.js#L25

<img width="1116" alt="image" src="https://github.com/Rhosys/openapi-explorer/assets/14797520/9b397659-d9b7-4b84-8d6c-b343e2bb0067">

**Comment by wparad** [comment]
Thanks for hint on the location of the issue. We've excluded numbers from the "copy magic", so copying these long strings of numbers should work as expected now.
