### ISSUE TITLE
Parameter values are retained between endpoint

### ISSUE THREAD

**Issue by gdec31** [Rhosys/openapi-explorer#168]
Hello, 
First, thank for the project is  really awesome.

I have a behavior that I didn't expect.
Parameter values are preserved between endpoints.
I have no problem with the parameter name being the same from one endpoint to another.

To reproduce :

- Set value to the parameter "roleId" of  https://rhosys.github.io/openapi-explorer/#?route=get-/v1/roles/-roleId-
- Change the endpoint sthat have a path parameter, like "Update access record"

Actual behavior : 

- The parameter value is retained even if the parameter is not the same

Expected behavior : 

- The parameter of the newly selected endpoint must be empty if the parameter name is not the same

**Comment by wparad** [comment]
Glad to hear it.

The good news is that's definitely a bug. We'll get someone on fixing that.

**Comment by gdec31** [comment]
Thank you for the quick fix.
