### ISSUE TITLE
CSS Editing

### ISSUE THREAD

**Issue by iasisalomon** [Rhosys/openapi-explorer#17]
I need to eliminate this borders from the nav-scroll, but there is no ::part to edit this.
![Screenshot from 2021-04-28 11-41-42](https://user-images.githubusercontent.com/48367845/116424135-a459e100-a817-11eb-8a3f-81e5c31b2abe.png)

**Comment by wparad** [comment]
Which border do you mean? The only borders in the nav-scroll are the horizontal line separators around the overview/api servers/authentication section. Is that what you are talking about?

**Comment by iasisalomon** [comment]
![Screenshot from 2021-04-28 11-41-42](https://user-images.githubusercontent.com/48367845/116465390-902bd900-a843-11eb-9843-1006181b85ab.png)

**Comment by wparad** [comment]
Confirmed, there is no css `part` for that, but we can add one.

**Comment by iasisalomon** [comment]
Please, whenever u can.
