### ISSUE TITLE
Be able to hide request example(s)

### ISSUE THREAD

**Issue by gdec31** [Rhosys/openapi-explorer#171]
Hello,

For my use I like to use the placeholder to show an example of a parameter even if I lose the content when I put the cursor over it.

But I have a duplicate information with the "**Example:**" and is too much in the spotlight.

![image](https://github.com/Rhosys/openapi-explorer/assets/26168420/295bf0b3-1932-4c01-a94a-c667c68156b3)

Is it possible to add an option to hide the request examples ? or to be able to manage this via CSS ?

**Comment by wparad** [comment]
I'm thinking about auto hiding the examples documentation below if there is only one and it's already going to show as the placeholder. Would something that make sense for you?

**Comment by gdec31** [comment]
Yes, that would make sense to me,

**Comment by wparad** [comment]
This has been completed and will be automatically available shortly.
