### ISSUE TITLE
Retain populated parameters when executing request that includes array parameters

### ISSUE THREAD

**Issue by nneul** [Rhosys/openapi-explorer#174]
Currently in the UI, when you execute a request that contains array parameters, the populated parameters are lost:

![image](https://github.com/Rhosys/openapi-explorer/assets/828492/cba1a81c-7e78-47c1-be36-97ffb0fe1ed2)

![image](https://github.com/Rhosys/openapi-explorer/assets/828492/c6e3f6b2-7886-4dc4-b996-4e56ce2feb0d)

Would be nice if this retained them. It does NOT appear to lose the parameter values if it is a simple string field.

**Comment by nneul** [comment]
![image](https://github.com/Rhosys/openapi-explorer/assets/828492/54dc8505-af03-4bb5-9c6a-547492d34d2d)

**Comment by wparad** [comment]
What do you mean by "lost", do you mean "consumed"? As in, after execution the populated values are no longer present?

Interesting, that is definitely a bug, can you include a minimal spec that exhibits this problem so we can solve it right away?

Thanks!

**Comment by nneul** [comment]
Example suitable to demo:

```
openapi: 3.0.0
info:
  description: Demo
paths:
  /api/test:
    get:
      parameters:
        - name: code
          description: 'demonstrate multiple parameters'
          schema:
            type: array
            items:
              type: string
            minItems: 1
          in: query
          style: form
          explode: true
          required: true
      produces:
        - application/json
```

**Comment by wparad** [comment]
Thanks for the minimal repro, I've pushed out a new version which is currently building and should be available shortly which will fix this problem. Please do let us know if for any reason this isn't working as you would expect.
