### ISSUE TITLE
Response examples are not rendered

### ISSUE THREAD

**Issue by accountForIssues** [Rhosys/openapi-explorer#178]
Spec: https://api.carbon.ai/openapi.json
Works: https://api.carbon.ai/redoc

(Happens with other specs as well but couldn't reproduce it consistently)

The response examples are not rendered in the endpoints area.

In the console I see this:

```
Uncaught (in promise) InternalError: too much recursion
    jr http://localhost:8001/openapi-explorer.min.js:3
    jr http://localhost:8001/openapi-explorer.min.js:3
    jr http://localhost:8001/openapi-explorer.min.js:3
    .... and so on
```

**Comment by wparad** [comment]
The problem is you haven't defined the `type` property in your `items` objects. As soon as you do that, the spec will automatically fix itself. However, we've added additional protection to resolve that. You can test it out as soon as the automated build runs in release `1.1`.

**Comment by wparad** [comment]
It's as I said, there are schema without the type attribute.
