### ISSUE TITLE
build: `regex-to-strings` minified is 151 KB vs `randExp.js` 9 KB, and 4k vs 3m weekly downloads

### ISSUE THREAD

**Issue by llllvvuu** [Rhosys/openapi-explorer#179]
Current bundle size:

```
Assets: 
  openapi-explorer.min.js (938 KiB)
  openapi-explorer.min.js.gz (248 KiB)
```

**Comment by wparad** [comment]
This looks like a request to change the dependency, we definitely can if that library offers the functionality we need here. What's the difference in usage, would that other library help us here?

**Comment by llllvvuu** [comment]
Hi @wparad great question, it's basically a drop-in replacement. Just opened a PR: https://github.com/Rhosys/openapi-explorer/pull/180
