### ISSUE TITLE
Slot documentation

### ISSUE THREAD

**Issue by iasisalomon** [Rhosys/openapi-explorer#18]
I was reading the docs and found "name" is replacing where "slot" should go.

div name="overview"
div name="authentication"
div name="servers"
div :name="${method}-${sanitizedPath}"

Also, I'm trying to implement the `method-sanitizedPath` slot, but remains unclear for me. Can you give me an example?

Thanks!

**Comment by iasisalomon** [comment]
For example, we would like to change the circled part with rich html.
![chrome_N1YBfUZAAe](https://user-images.githubusercontent.com/48367845/117233621-dbbd2480-adf9-11eb-832d-489e8afd8074.png)

**Comment by wparad** [comment]
> I was reading the docs and found "name" is replacing where "slot" should go.
> 
> div name="overview"
> div name="authentication"
> div name="servers"
> div :name="${method}-${sanitizedPath}"
> 
> Also, I'm trying to implement the `method-sanitizedPath` slot, but remains unclear for me. Can you give me an example?
> 
> Thanks!

I'm not sure I totally understand what you are looking for.

For sanitized path, it's the `path` with this replacement: https://github.com/Rhosys/openapi-explorer/blob/e43a90c23be4813d2d8381b59a95bc15573c2513/src/utils/common-utils.js#L13

```js
const sanitizedPath = path.replace(/[\s#:?&={}]/g, '-')
```

**Comment by iasisalomon** [comment]
Thanks!
