### ISSUE TITLE
Rendering openapi-explorer in Vitepress generates export not defined on build

### ISSUE THREAD

**Issue by glennsc** [Rhosys/openapi-explorer#187]
I can successfully render `openapi-explorer` inside [Vitepress](https://vitepress.dev) in the non-SSR dev mode using a markdown page like this:

```md
---
layout: page
sidebar: false
---
<script setup>
  import 'openapi-explorer';
</script>

<Clientonly>
  <openapi-explorer
    spec-url = "https://petstore3.swagger.io/api/v3/openapi.json"
    enable-console = false
    show-authentication = false
    show-server-selection = false
  >
  </openapi-explorer>
</ClientOnly>

```
It renders on the dev server but running `npm run docs:build` generates this error:

> ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/gs/dev/clients/uta/mdm-site/docs/.vitepress/.temp/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/gs/dev/clients/uta/mdm-site/node_modules/openapi-explorer/dist/lib/openapi-explorer.js:3:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Is this an openapi-explorer issue?  Or a Vitepress issue?  I should point out that if you look at the `/dist` folder the build outputs are there and `nom run docs:preview` seems to work.  But this fails CI and I'm wondering if there is an obvious thing to fix.
    
## Repo sample

https://github.com/glennsc/oa-test-1

**Comment by wparad** [comment]
It looks like vitepress is importing the wrong version, if it wants a `module` it should be importing the `esm` version, but it isn't. You force it to import it by using:

```js
import 'openapi-explorer/dist/es/openapi-explorer.js';
```

Can you let us know if that fixes the problem?

Alternatively you can use the commonjs version by using:
```js
require('openapi-explorer/dist/browser/openapi-explorer.min.js')
````

The openapi explorer releases three versions:
* 'openapi-explorer/dist/browser/openapi-explorer.min.js' - compiles to cjs
* 'openapi-explorer/dist/es/openapi-explorer.min.js' - compiled to esm
* 'openapi-explorer/dist/lib/openapi-explorer.min.js' - uncompiled

Your build tool chain should automatically be picking the correct one, either:
* It just is broken and isn't picking the right one
* None of these are working for vitepress and we need to do something else.

I have no idea which problem it is, but we can start by directly importing the `esm` version (or potentially one of the other two) and see if that fixes the problem. If it does then we'll have more information on how to go from there.

**Comment by wparad** [comment]
Instead of trying to fix the vitepress configuration, we've released a new version 1.2 that better supports this. You can find a working copy in the version: `1.2.610`

**Comment by glennsc** [comment]
Confirming that 1.2.610 works... as long as I keep that "forced" syntax you recommended.  Thank you!
```js
import 'openapi-explorer/dist/es/openapi-explorer.js';
```

**Comment by wparad** [comment]
Awesome, glad to hear it. Unfortunately we can't do anything more than that, it seems like there is some bug in vitepress. It might be worth opening a ticket with them based on your error and see if they have any suggestions.
