### ISSUE TITLE
Parameter Constraint line is only rendered under conditions

### ISSUE THREAD

**Issue by Xarno** [Rhosys/openapi-explorer#190]
The constraint line for path/query parameters is only rendered when „default“, „s“, „allowedValues“ or „pattern“ is set. (What is s?)

I have a query parameter which is in the open api.json like this. The utils function unpacks the constraint correctly. But the render condition is not true.
``` 
      {
          "name" : "lang",
          "in" : "query",
          "description" : "Two Letter Iso lang code. Lowercase",
          "schema" : {
            "maxLength" : 2,
            "minLength" : 2,
            "type" : "string"
          }
        } 
```
Source reference:
https://github.com/Rhosys/openapi-explorer/blob/599858df91c9e3c816426eec2290769e74a44ba1/src/components/api-request.js#L223-L227

**Comment by wparad** [comment]
Fixed, this will be available in the latest version as soon as the build completes.
