### ISSUE TITLE
Issue with code sample indentation

### ISSUE THREAD

**Issue by addshore** [Rhosys/openapi-explorer#196]
When providing the following code sample...

```
      x-code-samples:
        - lang: JavaScript
          label: JS + Axios
          source: |
            import axios from "axios";

            const options = {
              method: 'POST',
              url: 'https://api.foo.com/api/users/login',
              params: {include: 'user'},
              headers: {'Content-Type': 'application/json'},
              data: {username: 'user@example.com', password: 'abc123...'}
            };

            axios.request(options).then(function (response) {
              console.log(response.data);
            }).catch(function (error) {
              console.error(error);
            });
```

The code sample is rendered without indentation

![image](https://github.com/Rhosys/openapi-explorer/assets/3308769/5dedf72b-243d-4273-bd65-18245c26065a)

If I add an extra 2 spaces to the method line, some indentation appears

![image](https://github.com/Rhosys/openapi-explorer/assets/3308769/41b70b41-e3f3-4896-a091-bf510220e494)

However if I add these extra 2 spaces to all lines that require indentation, all indentation again disappears (as in the screenshot above)

**Comment by wparad** [comment]
_Awesome_. I know there are some magic there to get the padding correct, I'm a bit surprised by this result though. Of course that is a bug and will need to be fixed. The padding should be correctly aligned to match what has been entered (however it should be correctly shifted to the left to handle the discrepancies between the yaml and what the left-most indent should be.

I could imagine there is a just a small little one line bug somewhere.

**Comment by addshore** [comment]
Works great!
Many thanks!
