### ISSUE TITLE
Link from authentication slot (or custom slot) to the documentation of a route

### ISSUE THREAD

**Issue by addshore** [Rhosys/openapi-explorer#198]
I have an authentication slot defined

```
  return <openapi-explorer>
    <div slot="authentication">
      <OApiAuthentication handleAuthTokenChange={handleAuthTokenChange}/>
    </div>
    </openapi-explorer>
```

Which points to a `mdx` file with a line such as this

```
Authorization for API currently uses Bearer tokens generated from the `/users/login` endpoint.
```

I want to link to the reference to the endpoint, to the documentation for the endpoint.

I have tried the following markdown

```
Authorization for API currently uses Bearer tokens generated from the [`/users/login`](#?route=post-/users/login) endpoint.
```

Which appears to correctly switch the browser URL to http://localhost:8093/api-v1#?route=post-/users/login
However the page itself does not update, and I stay on the authentication page.

I guess my expectation here would the that openapi-explorer detects the link click or url change and takes me to the right place
It could again be that this is an issue with the way I am embedding the component within a nextja / nextra site, however I don't see any documentation on this behavior working or examples in authress or other examples

**Comment by addshore** [comment]
Many thanks for the hand holding

**Comment by wparad** [comment]
No problem at all, I was also curious if there was actually a problem here because I definitely hadn't personally tested this one.
