### ISSUE TITLE
Add sections to NavScroll

### ISSUE THREAD

**Issue by iasisalomon** [Rhosys/openapi-explorer#20]
We need to add new titles that open a section to the nav-scroll part and render to them rich HTML, just like overview. What is the correct way to do this?
![chrome_7i3qyrb54v](https://user-images.githubusercontent.com/48367845/117317422-e3afaf80-ae5f-11eb-9847-812d90e810f4.png)

**Comment by wparad** [comment]
Sounds like a great idea. We think it could be done reusing slots in a clever way, and dynamically including:
* custom section slot
* nav-bar slot

**Comment by wparad** [comment]
New functionality in release 0.4. If you find any issues with it, please create a new issue.
