### ISSUE TITLE
select tab by default on main-body

### ISSUE THREAD

**Issue by iasisalomon** [Rhosys/openapi-explorer#27]
Need to select tab by default on this menu. 

I would also like to add more of them (cURL or language snippets)
![2021-09-02_15-05](https://user-images.githubusercontent.com/48367845/131894768-c4afc44c-e14f-4f65-ae01-8000436c207a.png)

**Comment by wparad** [comment]
:+1:  Seems like a good idea to have this functionality available

**Comment by wparad** [comment]
There's a new property, make sure to set `default-schema-tab="body"`.
