### ISSUE TITLE
add examples label when applicable

### ISSUE THREAD

**Issue by iasisalomon** [Rhosys/openapi-explorer#29]
![2021-09-02_15-13](https://user-images.githubusercontent.com/48367845/131896045-865f0f62-36e9-4cc9-bab0-abec4add66ce.png)

**Comment by wparad** [comment]
I think this is a great idea, we would welcome a PR to help get this functionality included.

**Comment by wparad** [comment]
Since this body is not actually examples, we'll show this as valid requests to be made. Closing.
