### ISSUE TITLE
securitySchemes apiKey in=query adds as header

### ISSUE THREAD

**Issue by WORMSS** [Rhosys/openapi-explorer#30]
Using spec: [google-maps-platform-openapi3.json](https://raw.githubusercontent.com/googlemaps/openapi-specification/main/dist/google-maps-platform-openapi3.json)

States they have an apikey called key, in the query

![image](https://user-images.githubusercontent.com/1384537/132025196-ddec4eab-c6b2-44be-92e6-adc0b24c45cf.png)

I filled it in and it states apikey, called key

![image](https://user-images.githubusercontent.com/1384537/132025359-0aeed178-52b1-472c-b407-a172614a3098.png)

But it adds it to the header, and unfortunately causes a CORS error.. The CORS Error is actually correct (for once). If it were to add it to the query (as it should) I believe it wouldn't cause a CORS error, because if you omit the key completely, it doesn't add the additional header, and returns a access denied, (since the API key is missing)

![image](https://user-images.githubusercontent.com/1384537/132025463-ee84ee8a-7b1c-407d-a35d-1de5ea61fe3d.png)

```html
<!doctype html>
<html>
  <head>
    <script type="module" src="https://unpkg.com/openapi-explorer/dist/openapi-explorer.min.js"></script>
    <!-- Or use a local deployed copy -->
    <!-- <script type="module" src="node_modules/openapi-explorer/dist/openapi-explorer.min.js"></script> -->
  </head>
  <body>
    <openapi-explorer spec-url="https://raw.githubusercontent.com/googlemaps/openapi-specification/main/dist/google-maps-platform-openapi3.json"> </openapi-explorer>
  </body>
</html>
```

**Comment by wparad** [comment]
There was a bug here, and it should be resolved in the latest version. Thanks for the report.
