### ISSUE TITLE
Hide Operations Accordion when there are no tag groups to accordion

### ISSUE THREAD

**Issue by soumyajitsamanta** [Rhosys/openapi-explorer#35]
Hi,

Was using openapi-explorer to view some openapi spec files and could not collapse the operations tab/accordion in the menu.

The element in question is described below.

<img width="213" alt="Capture" src="https://user-images.githubusercontent.com/14129509/136555959-f9fe1a85-d60f-49c4-b916-81f2b6a21f16.png">

**Comment by wparad** [comment]
Please include a minimal spec and configuration to reproduce the problem. Also what browser and os?

**Comment by soumyajitsamanta** [comment]
Oh ok now i got it so collapse is for groups only, no problem then everything works fine. Can it be possible to hide that button if no tag groups are there as there is nothing to collapse? If not no problem. 

Thanks for help me and my colleagues will keep that in mind.
