### ISSUE TITLE
Are multiple API Versions supported

### ISSUE THREAD

**Issue by Layap** [Rhosys/openapi-explorer#44]
Is API Versioning support present in openapi-explorer? If yes, can you please share an example? If no, is it on the roadmap?

**Comment by wparad** [comment]
It is definitely feasible for the explorer to easily support multiple versions of your api. However the exact implementation would be determined based on how your api actually is versioned.

What does versioning mean to you? Once we understand that, we can give a recommendation on possible configuration options.

**Comment by wparad** [comment]
Closing as multiple versions are supported.
