### ISSUE TITLE
Support relative path for load spec

### ISSUE THREAD

**Issue by lucianojs** [Rhosys/openapi-explorer#51]
This HTML does't work:

```
<!doctype` html>
<html>
  <head>
    <script type="module" src="https://unpkg.com/openapi-explorer/dist/openapi-explorer.min.js"></script>
  </head>
  <body>
    <openapi-explorer spec-url="openapi.yaml"></openapi-explorer>
  </body>
</html>
```

I deploy in many servers and I need support for relative paths.

**Comment by wparad** [comment]
Is there something preventing you foining `window.origin` with the `openapi.yaml` path to get the absolute one before passing it in here?

**Comment by lucianojs** [comment]
Is there a sample how I do this? I didn't see any examples.

I compared it with other web components like elements-api, rapi-doc and redoc and they all work with absolute and relative paths.

**Comment by wparad** [comment]
This should work, all you'll need to do is construct the url you want.

```html
<html>
  <script src="https://unpkg.com/openapi-explorer/dist/openapi-explorer.min.js" type="module" defer></script>

  <body>
    <openapi-explorer show-components="true" default-schema-tab="body"></openapi-explorer>
    <script>
      document.addEventListener('DOMContentLoaded', async (event) => {
        const url = "FullUrlPath";
        await document.getElementsByTagName("openapi-explorer")[0].loadSpec(url.toString());
    </script>
  </body>

</html>

```

**Comment by lucianojs** [comment]
I will try this. Thanks.

**Comment by wparad** [comment]
@lucianojs was this able to resolve the problem? I want to understand the importance of the issue is.

**Comment by lucianojs** [comment]
@wparad I solved the problem with your example.

The proposed alternative would be a legal feature, but it is not an impediment to use.
