### ISSUE TITLE
Add extended example support for request parameters

### ISSUE THREAD

**Issue by wparad** [Rhosys/openapi-explorer#55]
https://github.com/rapi-doc/RapiDoc/pull/759/files#diff-8e0994f875e96985adc7136b31e1eb6fe2ba0b4ec504a11d5bfa5044d33fe600R234

For example:
![image](https://user-images.githubusercontent.com/5056218/171824662-fcd6ff8c-00dd-4257-8533-de44275819d2.png)

```yaml
description: |
                `Lorem ipsum dolor sit amet` consectetur adipisicing elit.
                1. Animi alias iste
                1. minus iure
                1. assumenda quisquam
                1. qui cum id ab nesciunt
                _Impedit voluptatum asperiores obcaecati blanditiis_ perferendis error repudiandae odit, veniam ab culpa exercitationem eaque,
                > repellat **laboriosam sequi dolor doloribus** voluptas
                 natus hic fugiat incidunt.
                - laborum odio dolore
                - corrupti tenetur
                - nostrum aut sunt,
                quis vel neque. Vitae maxime aut assumenda ipsum.
```

**Comment by silverbullettruck2001** [comment]
Any ETA on when this will be supported?  Will it be available on all areas that support the `examples` keyword (requests body, response body, etc)?

**Comment by silverbullettruck2001** [comment]
In the Bodies you display `Default`, `Allowed` and `Constraints` at a property level.  Couldn't you provide an additional element for `Example` on each property and display the array of provided values?

**Comment by wparad** [comment]
Sounds reasonable, which is more important, the body examples or the request parameters?

**Comment by silverbullettruck2001** [comment]
I would probably weigh body examples more important for me.  Although, I would definitely like the ability to do both eventually.  Do you want a separate issue logged for body examples?

**Comment by wparad** [comment]
> I would probably weigh body examples more important for me. Although, I would definitely like the ability to do both eventually. Do you want a separate issue logged for body examples?

@silverbullettruck2001 yes please

**Comment by silverbullettruck2001** [comment]
created #72

**Comment by accountForIssues** [comment]
@wparad Would love to have this feature for

Swagger implements it in this manner:

![image](https://github.com/Rhosys/openapi-explorer/assets/52367365/8f9a7a2d-1650-471d-891c-e64e7bbdce16)

Minimal spec:
```
{
    "openapi": "3.0.2",
    "info": {
        "title": "Beta API access",
        "description": "Lorem ipsum"
    },
    "paths": {
        "/api/users/{user_id}/": {
            "get": {
                "tags": [
                    "users"
                ],
                "parameters": [
                    {
                        "description": "id of the user",
                        "required": true,
                        "schema": {
                            "title": "user id",
                            "type": "string",
                            "description": "id of the user"
                        },
                        "examples": {
                            "eg1": {
                                "summary": "example with unique id",
                                "value": "05dbd224-b60f-4979-ae44-225554ab6ade"
                            },
                            "eg2": {
                                "summary": "example with friendly name 1",
                                "value": "@username"
                            },
                            "eg3": {
                                "summary": "example with friendly name 2",
                                "value": "username"
                            }
                        },
                        "name": "user_id",
                        "in": "path"
                    }
                ]
            }
        }
    },
    "tags": [
        {
            "name": "users"
        }
    ]
}
```

**Comment by wparad** [comment]
This has now been fixed:
![image](https://github.com/Rhosys/openapi-explorer/assets/5056218/5554a53f-fbb2-4289-baa3-41adfdd7df55)

If there are issues with this please do let us know.
