### ISSUE TITLE
Not working for React

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#56]
I tried using this project by creating a new React app and pointing it at a OpenAPI spec file however it is not working.  I have tried using React 17 and 18.  I also tried using Vue and Vite.  No matter what I do I get the same error.  I could get it working with vanilla HTML but I would rather not use that option.  

Here is the error I am getting, any suggestions would be welcome.  Thanks!

```
Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/safe-buffer/index.js (index.js:12:12)
    at __require (chunk-M5PF3ZFT.js?v=08a7ed97:28:50)
    at node_modules/randombytes/browser.js (browser.js:15:14)
    at __require (chunk-M5PF3ZFT.js?v=08a7ed97:28:50)
    at security-scheme-template.js:5:25
```

**Comment by wparad** [comment]
It isn't pulling in `Buffer` which most web packers will auto patch. It would help if you could share which one you want to use, and we can try to repro it. Webpack is supposed to do this automatically. For esbuild/vite there's a pretty good example of how to overcome this problem: https://github.com/Authress/authress-login.js/blob/release/1.2/docs/troubleshooting.md

Vite:
```js
import RollupNodePolyFill from 'rollup-plugin-polyfill-node';
import NodeGlobalsPolyfillPlugin from '@esbuild-plugins/node-globals-polyfill';

export default defineConfig({
  build: {
    rollupOptions: {
      plugins: [
        RollupNodePolyFill()
      ]
    }
  },
  optimizeDeps: {
    esbuildOptions: {
      define: {
        global: 'globalThis'
      },
      plugins: [
        NodeGlobalsPolyfillPlugin({ buffer: true })
      ]
    }
  },
})
```

If that doesn't work let us know. Either way we'll keep this issue open until the solution is automated.

**Comment by jmcpeak** [comment]
Hey,

I was helping @silverbullettruck2001 track this down.

Here's a link to GitHub repo that has the issue:

https://github.com/jmcpeak/openapi-explorer

And here's a running example of it in the CodeSandbox (it is linked to the GitHub repo):

https://codesandbox.io/s/nervous-bardeen-izs30c?file=/src/App.jsx

You'll notice that the CodeSandbox displays just a white screen, but, if you comment out this line and refresh it works:

```javascript
import "openapi-explorer";
```

**Comment by wparad** [comment]
@jmcpeak I think I've found the problem with one of the dependencies. From your repro (thank you for that!) it looks like the new version `0.8.284` works with it. I would appreciate the confirmation before we close the ticket.

**Comment by jmcpeak** [comment]
@wparad - confirmed, that fixed it, thank you!
