### ISSUE TITLE
API Servers List

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#58]
When `openapi-explorer` displays, the list of API Servers includes all the entries in the provided OpenAPI file, but it also includes an entry for the server that is hosting the documentation.  Is there a way to only show what is in the openapi file?

**Comment by wparad** [comment]
That seems like a bug that should be fixed. I can imagine it should only populate with the docs location when the server list is empty.

**Comment by wparad** [comment]
This has been fixed. If you find any issues with the new version, please don't hesitate to post an update here.
