### ISSUE TITLE
Top Level Collapse/Expand

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#60]
Currently the `Operations` item in the left nav has a carot that allows you to expand/collapse the entire tree, but if you scroll down the list and want to expand/collapse you have to scroll all the way back up to the top to see the `Operations` carot again.  Could you have an `expand` and `collapse` option that is in the `Search` area that can expand and collapse as needed without having to scroll?

**Comment by wparad** [comment]
Changed this component to be sticky at the top. Should solve everything here.
