### ISSUE TITLE
Nav Shortcuts

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#63]
Could you provide a way to get to the top of the list of operations quickly?  Our list of `Operations` is over 100 and if you go to the bottom of the list you have a lot of scrolling to get back to the top.  Maybe some sort of hover button that appears at the bottom of the nav when you scroll down that will take you back to the top?  Or a link next to the word `Operations` that is now sticky that says `Top` to take you back to the top?

**Comment by wparad** [comment]
I wonder if we should do something similar to the stripe API experience: https://stripe.com/docs/api/payment_methods

Two modes:
* all expanded, let's you collapse them
* only one tag expanded at a time, selecting a different one opens that section with the list but closes the other sections

I'd venture that would be a better experience, would that be an acceptable solution?

**Comment by silverbullettruck2001** [comment]
I think it would get closer, but I think we would still have a struggle because of how many `Operations` we have.  The scrolling just gets excessive.  Anything that would aid in navigating up the page quicker for the user would be a great help.  The best I can do now is suggest using the `Home` button on the keyboard, but that's tricky because you have to make sure to click one of the operations to make it work.

**Comment by wparad** [comment]
How many operations per tags do you have?

**Comment by silverbullettruck2001** [comment]
187...it is higher than we want, we are trying to consolidate them into fewer tags.  Even after we do that, I don't believe we will be considerably lower...maybe down to 150?

**Comment by wparad** [comment]
150 operations per tag? You probably like 10~20 tags? So you have over 1000 operations in your one API? Wow.

Right now I'm thinking the easiest thing to implement would be a "clickable link" next to the **OPERATIONS** header. Fwiw, you can overwrite the operations header (because it is a slot) and already add that, you don't have to wait for us to add something in here to support that.

(There might even be a slot at the bottom of the API, if there isn't, perhaps that could be the easiest thing for us to add instead.)

**Comment by silverbullettruck2001** [comment]
Sorry, I may have misread your question.  I equate `operations = tags`, is that incorrect?  I have about 7 paths per tag.  But still, we have A LOT of endpoints on our API, maybe not 1000, but it is up there.

Do you have some sort of example of how to accomplish the `clickable link`?

**Comment by wparad** [comment]
ha, no an `operation` is like `get /resource/endpoint` not a tag. 7 paths per tag, :+1:. at 150 paths, and ~7/tag that's still ~21 tags.

If you only have 21 tags being displayed a time + 7 paths, that's only ~28 "clickable objects". I wouldn't think "srcoll to top" would be necessary.

as far a clickable link, in `0.8.300` I've added a slot for `operations-header`. Here's how you can override the header and add a clickable button to "scroll to top"
```html
<openapi-explorer>
  <div slot="operations-header">
    <div>OPERATIONS</div><br>
    <div><button onclick="onClick()" style="padding-left: 10px; color: #FBAF0B; text-decoration: none; font-size: 16px;">click me</button></div>
  </div>
</openapi-explorer>
<script>
    function onClick(event) {
        document.getElementsByTagName("openapi-explorer")[0].setAttribute('explorer-location', 'overview');
    }
</script>
```

In your case, you'll obviously want this in react, but I'm sure that's no problem to dynamically set the `explorer-location` attribute from javascript.

**Comment by silverbullettruck2001** [comment]
Ok, so based on your definitions, I have 517 unique paths and I am hoping to get down to 150 unique tags, so I will have 150 collapsable items that are showing in the left hand nav, that's why I have the scrolling issue.  Sorry I wasn't speaking the same terms.  I think this should clarify it now though.

I will start testing with the `0.8.300` build and use your example to see what I can come up with and report back.  Thanks again for your help.  It is very appreciated!

**Comment by wparad** [comment]
I know it isn't everything, but with the suggestion I previous made and a new change in `0.8.301` to have the Stripe like collapse experience, I think this is going to be a lot better

![0 8 301-collapse-functionality](https://user-images.githubusercontent.com/5056218/180504937-7f21dccb-120b-4102-94e2-7c3df528346e.gif)

**Comment by silverbullettruck2001** [comment]
@wparad could this be made so you can specify if you want to have the `Operations` section loaded so that they are all collapsed by default or expanded by default?  Right now it defaults to expanded, but it would be nice to be able to have that customizable, especially now with the new change you made.  I can open a separate ticket if you want?

**Comment by wparad** [comment]
> @wparad could this be made so you can specify if you want to have the `Operations` section loaded so that they are all collapsed by default or expanded by default? Right now it defaults to expanded, but it would be nice to be able to have that customizable, especially now with the new change you made. I can open a separate ticket if you want?

@silverbullettruck2001 :+1: separate ticket
