### ISSUE TITLE
Upgrading to `0.9.3xxx` breaks

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#64]
I was updating to the `0.9.310` version and after updating it no longer works.  I tried rolling back, I went to `0.9.303` and it was still broke.  I rolled back to `0.8.302` and it worked again.  I didn't make any changes other than changing the `openapi-explorer` version.  Here is the console error that is logged on any of the `0.9.3xx` versions:

```
Uncaught ReferenceError: require is not defined
    at index.bb995387.js:1750:14
    at index.bb995387.js:1:470
    at index.bb995387.js:3623:1544
```

Here is a screenshot of where the error was thrown:
![image](https://user-images.githubusercontent.com/26559157/180786784-77193077-8424-41ad-8704-23bce71976a6.png)

**Comment by silverbullettruck2001** [comment]
Now the page won't load the OpenAPI spec.  It say's its not there, but I have verified it is.  Also, I only changed the version and if I rollback to `0.8.302` it works fine.  It looks like there is something wrong with the Buffer?  Here's the error being thrown:
![image](https://user-images.githubusercontent.com/26559157/180790946-4f4abb8c-ab7c-4a6d-bb43-d7448604a61f.png)

**Comment by wparad** [comment]
`Buffer` is not web compatible, but almost ever web packer (like webpack) has a strategy for inserts. If don't have Buffer, time to polyfill.

The solution for webpack is:

```js
module.exports = { 
  plugins: [new webpack.ProvidePlugin({ Buffer: ['buffer', 'Buffer'] })]
};
```

The thing is this isn't a new dependency, so I'm not sure why it's an issue only now. We can look into that, but in the meantime, (if you aren't using webpack, we can find you the alternative patch strategy for Buffer).

I don't think it is necessary, but you also could ensure the correct transpiling (by adding `transpileDependencies: ['openapi-explorer']` to your configuration. I don't know what the corresponding react version is)

Alternatively, if you aren't getting the mileage out of the raw unpackaged version, you can use the "pre-compiled" version that's available in the `dist/openapi-explorer.min.js` which always includes all the dependencies built in.
