### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#66]
The link in the `README.md` file for `Generate the open specification necessary for this library` does not work. 
 It currently points to `https://github.com/Rhosys/openapi-explorer/blob/release/0.9/docs/examples#openapi-specification-generation` which doesn't appear to be valid.  It's small, but just wanted to mention it so it can be addressed at some point.

**Comment by wparad** [comment]
Thanks the heads up. fixed.
