### ISSUE TITLE
External Content Examples

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#68]
Could you provide some example documentation on how to include external content?

**Comment by wparad** [comment]
What do you mean by this?

**Comment by silverbullettruck2001** [comment]
In your `readme` it says:
```
Plenty of customization options
Add external contents at the top and bottom of the document, extensible with images, link, text, and any framework components
```

**Comment by wparad** [comment]
There are tons of `slots`, which are littered throughout the component. I'm going to take this as a hint to improve the wording here. If there is something specific you are trying to do, I might be able to give some advice.

Slot examples are available here: https://github.com/Rhosys/openapi-explorer/blob/main/docs/documentation.md#slots

Of course if there is something not clear, happy to improve it with a specific example.

**Comment by wparad** [comment]
There are two relevant slots, which should already be documented in the `slots` documentation, but I will repeat here for the benefit of this ticket:

```html
<div slot="nav-section">Navbar section name</div>

<div slot="custom-section">
    <div>
        main panel display content
    </div>
</div>
```

You can have both be multiple lines and change the navigation or change the display in the main area, as you select different options.

Perhaps it makes sense to look into doing that we the `nav-section`/`custom-section` and we can go from there?

**Comment by silverbullettruck2001** [comment]
@wparad Is there a way to make a slot expand and collapse to other slots?  Similar to how `Operations` works, except providing a way to organize custom documentation that has a hierarchy.

**Comment by silverbullettruck2001** [comment]
@wparad along those same lines, is it possible to have multiple `nav-section` slots?  I tried doing something like below, but it just displays the content from both of the `custom-section` slots at the same time.

```
  <div slot='nav-section'>Nav Option1</div>

  <div slot='custom-section'>
    <div>
      <iframe src='test.html' />
    </div>
  </div>

  <div slot='nav-section'>Nav Option2</div>

  <div slot='custom-section'>
    <div>
      <iframe src='test.html' />
    </div>
  </div>
```

**Comment by wparad** [comment]
The HTML spec does not support this, so what you'll want to do instead is create your own nav sections using one `nav` element to display the right content as you would if you wrote this yourself.

```html
<div slot='nav-section'>
  <div @click="showNavSection1()">Option 1</div>
  <div @click="showNavSection2()">Option 2</div>
</div>

<div slot='custom-section'>
    <div v-if="showNavSection1">
      <iframe src='test.html' />
    </div>
    <div v-if="showNavSection2">
      <iframe src='test2.html' />
    </div>
  </div>
```

That being said if there are relevant api specification level sections that would make sense for every api, we could just add those into the spec, or allow you to overwrite them.

**Comment by wparad** [comment]
I'm not sure it exists, but if it would help to fire an event, let me know, although I'm assuming this should be good enough.
