### ISSUE TITLE
Cannot load from unpkg.com anymore

### ISSUE THREAD

**Issue by max-mathieu** [Rhosys/openapi-explorer#69]
Context: we're not importing the API explorer via npm in some SPA, but directly load it from unpkg.com in a static page

So far this import looked like https://unpkg.com/openapi-explorer/dist/openapi-explorer.min.js (no version specified as this allowed us to always get the latest improvements you've added without having to bump up versions and deploy again), but changes made in https://github.com/Rhosys/openapi-explorer/commit/fbdfa9f1c07702ff893f1c55dc4c6e499a5cd4db#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fR68 changed the path from `/dist/` to `/dist/browser/`

The fix on our end is easy, but thought I'd create an issue just in case someone is using it the same way we do and is wondering what's going on.

**Comment by wparad** [comment]
Sounds good, I'll close it then. In general you want to include version in the url to prevent future breakages.

`https://unpkg.com/openapi-explorer@0.9.319/dist/browser/openapi-explorer.min.js`

or at least include the minor version:

`https://unpkg.com/openapi-explorer@0.9/dist/browser/openapi-explorer.min.js`

Please avoid YOLOing with the "latest version"
