### ISSUE TITLE
Recursive model fails to load in latest 0.9 version

### ISSUE THREAD

**Issue by max-mathieu** [Rhosys/openapi-explorer#70]
Hi there -- me again :)

As we were fixing our other issue with unpkg (see #69) we realized that the docs for some of our endpoints are failing to load. We traced that to them being recursive, and they fail with
```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at Mt (callback-template.js:4:1)
    at Ft (callback-template.js:4:1)
    at Ft (callback-template.js:4:1)
    at Ft (callback-template.js:4:1)
    at callback-template.js:4:1
    at Array.map (<anonymous>)
    at Ft (callback-template.js:4:1)
    at Ft (callback-template.js:4:1)
    at Ft (callback-template.js:4:1)
```

I've reverted to 0.8 and it's fine. How can I help best? find the exact version that starts failing? Putting together a minimal reproducing definition will take me a bit of time, but happy to work on it if that's the best option

**Comment by wparad** [comment]
I can definitely believe there is a bug with the callback-template.

Don't worry about finding the exact version, I don't think anything related to callback templates has exactly changed, and we can do the investigation in any case. But I think we need see at least a spec, don't worry about the minimal one, just anything would be good start, if you can share.

**Comment by max-mathieu** [comment]
hi @wparad, this below is enough to trigger the issue:
```
openapi: 3.0.1
info:
  title: Test API
  description: Test
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "0.1"
paths:
  /comments:
    get:
      summary: List comments
      responses:
        200:
          description: Successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/CommentList'
components:
  schemas:
    CommentList:
      type: array
      items:
        $ref: '#/components/schemas/Comment'
    Comment:
      type: object
      properties:
        author:
          type: string
          example: Bob
        message:
          type: string
          example: Hello
        replies:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
```

Things are fine unless you click on `GET /comments`, where it triggers the same `Maximum call stack size exceeded`

Hope this helps

**Comment by wparad** [comment]
This should be resolved in the new version. Thank you for reporting this. `0.9.325`
