### ISSUE TITLE
Root `security` field ignored

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#73]
I am trying to use the `Execute` button to send requests to the API via `openapi-explorer`.  I have the details set in the spec to use `Basic` auth.  I made sure to go to the `Authorization` screen, enter in the credentials, and click `Set`.  However, when I go to make a request on one of the endpoints, it fails.  When I go to the `CURL` tab in the UI, it shows the command, but there is nothing listed for the `Authorization` header.  There is a line for the `Accept` header, which is needed for our API.  

Below is a link to a sandbox setup where you can recreate this.  Let me know if there's anything I need to change to get this to work correctly.

[sandbox link](https://codesandbox.io/s/working-openapi-explorer-ys6pxd?file=/src/App.jsx)

**Comment by wparad** [comment]
It's just missing the interpretation of the `security` field at the top level root of the document. No idea why it isn't being cascaded down automatically.
