### ISSUE TITLE
Nestable Nav Section slots

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#79]
Create a way to have parent/child relationships between a parent `nav-section` slot and zero-to-many child `nav-section` slots.  This should allow grouping together of documentation and allow for collapsing and expanding of the children so that the entire list of `nav-section` slots need to be shown and take up screen real estate all the time.  There should be a default collapse/expand setting like there is with components and operations.

The use case for this is that there is a need for grouping and displaying related documentation if you have a considerable number of custom documentation pages for different areas of an API.  For instance if you have a pet store and there is a single API that has endpoints for `retail`, `grooming` and `training` and you have documentation for each of those areas of the API.  The documentation needs to be grouped by the particular area it belongs and then only show when you click on the `nav-section` associated with that area.

It would be great to have this functionality sometime before the end of the year, if possible.

**Comment by wparad** [comment]
Every nav tag component is already slottable. So you can already override what it is in there put custom other logic in. If there is something specific that is stopping you from doing that we should definitely provide improvements, but at this moment isn't exactly clear what that would be (if anything).

As far as additional functionality, it isn't clear from what you have provided what this would even look like. If you have an idea for an improved user experience, please share concrete UX flow diagrams in figma or another tool that can convey how exactly this would look.

By _"endpoints"_ I'm going to assume you meant **tags** `retail`, `grooming`, etc...
Given that there is already full support for `<div slot="nav-${tagName}" />` slotting. An example of this could be:
```html
<div slot="nav-tag--retail">
  Retail
  <a>Other Link</a>
  <a>Other Link</a>
  <div>
    <h3>Paths</h3>
    <span>GET /</span>
    <span>POST /</span>
    ...
  </div>
</div>
```

Alternatively, I've enabled the functionality to support the `tag` description, so if you update the `description` for the tag, you'll see it as an expanding view in the navbar, but also visible in the right navigation panel.

I'me assuming all of this is sufficient, so I'm going to close this issue.

**Comment by silverbullettruck2001** [comment]
@wparad below is a screenshot of what I am trying to accomplish.  As you can see there would be a main "nav-section" group, and within it are multiple links that would belong to that group.  In my original example, there could be a "nav-section" for "grooming" and then below that there could be one or more sub documents that discuss different aspects of "grooming".  There could be other main groups with sub documents in each.  This would be expandable and collapsible to make the UI cleaner when they don't need to be displayed.  Is this something that can be done with existing functionality?  If so, could you provide some guidance on how this would be achieved?  As you can see, this isn't specific to an endpoint as it may discuss many endpoint details, but I need to be able to organize it logically so that the user can find it without extensive scrolling.  Thoughts?

![image](https://user-images.githubusercontent.com/26559157/185758465-2eadf788-36c3-4bfd-be91-f53494561245.png)

**Comment by wparad** [comment]
Does the `nav-section` slot not solve for this?

**Comment by silverbullettruck2001** [comment]
I can see how the `nav-section` would solve creating the `My Custom Doc Group`, but how would it deal with the expand/collapse and the nested links that display when expanded?

**Comment by wparad** [comment]
@silverbullettruck2001, I'm not sure I'm following the issue. Are you asking how you would write html and JavaScript to have a list of buttons that change your html elements when clicked? You can put html in the custom nav slot, not just text.

You can write that functionality, right?

Or are you asking a more nuanced question?
