### ISSUE TITLE
allOf/oneOf component schemas are not rendered correctly.

### ISSUE THREAD

**Issue by lucianojs** [Rhosys/openapi-explorer#81]
When using version 0.8.291, this model is shown for an endpoint:

![Captura de tela de 2022-08-12 20-30-11](https://user-images.githubusercontent.com/5367385/184456842-3ad58dba-6aaa-42e9-8246-470023af2ae4.png)

After I change for newer version, 0.9.355, the content in array is empty

![Captura de tela de 2022-08-12 20-30-42](https://user-images.githubusercontent.com/5367385/184456894-9d75a2e8-5604-4aaa-8939-fad84638b81d.png)

The endpoint is Evento - Listar - GET **/dte/{chave}/eventos**

https://doc.dte-hml.infraestrutura.gov.br/api/v1/openapi_bundle.yaml

**Comment by wparad** [comment]
Hmm, it isn't showing as an array either. Thanks for the reference spec. It's worth noting we had to switch some internal libraries to better support 3.1. No idea what's going on yet, but we'll take a look.

**Comment by wparad** [comment]
It was a bit challenging to make sure I caught all of the problem without a minimal repro spec, but #86 should have resolved almost everything. If you are still seeing an issue, it would help provide a minimal spec with the problem so that we can better investigate.

**Comment by lucianojs** [comment]
resolved almost everything.

The only issue is a few properties without types and descriptions.

When I make a minimal spec with the problem I will open another issue.

Thanks.

**Comment by wparad** [comment]
Glad to hear it.
